<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use Faker\Factory as Faker;
class CarSeeder extends Seeder
{
    public function run()
    {

        $faker = Faker::create();
          DB::table('cars')->insert([
              'color' => 'نيلي',
              'model' => $faker->numberBetween(1900,2017),
              'numberOfKillos' => $faker->numberBetween(30,100),
              'thumbnail' =>  'car1.jpg',
              'car_images' =>  json_encode(['car1_1.jpg', 
                                            'car1_2.jpg',
                                            'car1_3.jpg',  
                                                ]),
              'description' => $faker->sentence(8),
              'carPosition'=> $faker->sentence(8),
              'status' => '0',
              'brand_id' => $faker->numberBetween(1,5),
              'series_id' => $faker->numberBetween(1,4),
              'category_id' => '1',
          ]);
          DB::table('cars')->insert([
            'color' => 'أبيض',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'car2.jpg',
            'car_images' =>  json_encode(['car2_1.jpg', 
                                            'car2_2.jpeg',
                                            'car2_3.jpg',  
                                        ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '1',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '1',
          ]);

          DB::table('cars')->insert([
            'color' => 'أزرق',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'car3.jpg',
            'car_images' =>  json_encode(['car3_1.jpg', 
                                          'car3_2.jpg',
                                          'car3_3.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '1',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '1',
          ]);

          DB::table('cars')->insert([
            'color' => 'أحمر',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'car4.jpg',
            'car_images' =>  json_encode(['car4_1.jpg', 
                                          'car4_2.jpg',
                                          'car4_3.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '1',
          ]);

          DB::table('cars')->insert([
            'color' => 'أزرق',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'car5.jpg',
            'car_images' =>  json_encode(['car5_1.jpg', 
                                          'car5_2.jpg',
                                          'car5_3.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '1',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '2',
          ]);

          DB::table('cars')->insert([
            'color' => 'أزرق',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'car5.jpg',
            'car_images' =>  json_encode(['car5_1.jpg', 
                                          'car5_2.jpg',
                                          'car5_3.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '1',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '1',
          ]);

          DB::table('cars')->insert([
            'color' => 'أبيض',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'hyundai_caunty_3.webp',
            'car_images' =>  json_encode(['hyundai_caunty_1.webp', 
                                          'hyundai_caunty_2.webp',
                                          'hyundai_caunty_4.webp',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '4',
          ]);

          DB::table('cars')->insert([
            'color' => 'أبيض',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'toyota_camry_1.webp',
            'car_images' =>  json_encode(['toyota_camry_2.webp', 
                                          'toyota_camry_3.webp',
                                          'toyota_camry_4.webp',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '1',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '1',
          ]);
          
          DB::table('cars')->insert([
            'color' => 'أبيض',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'toyota_hilux_4.webp',
            'car_images' =>  json_encode(['toyota_hilux_1.webp', 
                                          'toyota_hilux_2.webp',
                                          'toyota_hilux_3.webp',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);

          DB::table('cars')->insert([
            'color' => 'كاكي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'toyota_land_cruiser_4.webp',
            'car_images' =>  json_encode(['toyota_land_cruiser_3.webp', 
                                          'toyota_land_cruiser_2.webp',
                                          'toyota_land_cruiser_1.webp',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '1',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);

          DB::table('cars')->insert([
            'color' => 'كحلي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'hyundai_accent_1.webp',
            'car_images' =>  json_encode(['hyundai_accent_2.webp', 
                                          'hyundai_accent_3.webp',
                                          'hyundai_accent_4.webp',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '1',
          ]);

          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'hyundai_creta_1.webp',
            'car_images' =>  json_encode(['hyundai_creta_2.webp', 
                                          'hyundai_creta_3.webp',
                                          'hyundai_creta_4.webp',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '1',
          ]);

          DB::table('cars')->insert([
            'color' => 'أبيض',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'daihatsu_gran_3.webp',
            'car_images' =>  json_encode(['daihatsu_gran_1.webp', 
                                          'daihatsu_gran_2.webp',
                                          'daihatsu_gran_4.webp',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '4',
          ]);

          DB::table('cars')->insert([
            'color' => 'أبيض',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'volvo_fh_1.jpg',
            'car_images' =>  json_encode(['volvo_fh_2.jpg', 
                                          'volvo_fh_3.jpg',
                                          'volvo_fh_4.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '1',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);

          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' =>    'volvo_fh16_1.jpg',
            'car_images' =>  json_encode(['volvo_fh16_2.jpg', 
                                          'volvo_fh16_3.jpg',
                                          'volvo_fh16_4.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);

          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'volvo_fh16_1.jpg',
            'car_images' =>  json_encode(['volvo_fh16_2.jpg', 
                                          'volvo_fh16_3.jpg',
                                          'volvo_fh16_4.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'taxi4.jpg',
            'car_images' =>  json_encode(['taxi1.jpg', 
                                          'taxi2.jpg',
                                          'taxi3.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '2',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'taxi8.jpg',
            'car_images' =>  json_encode(['taxi7.jpg', 
            'taxi5.jpg',
            'taxi6.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '2',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'taxi9.jpg',
            'car_images' =>  json_encode(['taxi10.jpg', 
                                          'taxi11.jpg',
                                          'taxi12.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '2',
          ]);

          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'babor1.jpg',
            'car_images' =>  json_encode(['babor2.jpg', 
                                          'babor3.jpg',
                                          'babor4.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'babor5.jpg',
            'car_images' =>  json_encode(['babor6.jpg', 
                                          'babor7.jpg',
                                          'babor8.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'babor9.jpg',
            'car_images' =>  json_encode(['babor2.jpg', 
                                          'babor5.jpg',
                                          'babor4.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'babor5.jpg',
            'car_images' =>  json_encode(['babor2.jpg', 
                                          'babor7.jpg',
                                          'babor9.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '3',
          ]);

          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'bus1.jpg',
            'car_images' =>  json_encode(['bus2.jpg', 
                                          'bus3.jpg',
                                          'bus4.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '4',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'bus5.jpg',
            'car_images' =>  json_encode(['bus6.jpg', 
                                          'bus7.jpg',
                                          'bus8.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '4',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'bus9.jpg',
            'car_images' =>  json_encode(['bus10.jpg', 
                                          'bus11.jpg',
                                          'bus12.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '4',
          ]);
          DB::table('cars')->insert([
            'color' => 'رصاصي',
            'model' => $faker->numberBetween(1900,2017),
            'numberOfKillos' => $faker->numberBetween(30,100),
            'thumbnail' => 'bus8.jpg',
            'car_images' =>  json_encode(['bus2.jpg', 
                                          'bus7.jpg',
                                          'bus10.jpg',  
                                            ]),
            'description' => $faker->sentence(8),
            'carPosition'=> $faker->sentence(8),
            'status' => '0',
            'brand_id' => $faker->numberBetween(1,5),
            'series_id' => $faker->numberBetween(1,4),
            'category_id' => '4',
          ]);
    }

}
